### PR TITLE
Fix pipeline project issues

### LINKED ISSUE #16: NPE in BenchmarkPublisher.getRawResults
When trying to execute the benchmark step, it fails with the following exception:

```java
java.lang.NullPointerException
	at org.jenkinsci.plugins.benchmark.core.BenchmarkPublisher.getRawResults(BenchmarkPublisher.java:354)
	at org.jenkinsci.plugins.benchmark.core.BenchmarkPublisher.perform(BenchmarkPublisher.java:211)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The build step:
```groovy
benchmark altInputSchema: '', altInputSchemaLocation: '', inputLocation: 'test.json', schemaSelection: 'defaultSchema', truncateStrings: false
```

`test.json` file is a static file in root of the workspace with the example result json inside (https://github.com/jenkinsci/benchmark-plugin/blob/master/doc/EXAMPLE_SCHEMA_JSON_DEFAULT.md#example-of-result-file-to-parse).

* the commit for more context: https://github.com/ipfs/go-ipfs/pull/4530/commits/826fcab29b717a9e427dbe7d39f7f18dca3dcde5
* build console: https://ci.ipfs.team/job/IPFS/job/go-ipfs/job/PR-4530/198/console (exception at the bottom)

### PR DESCRIPTION
**Pull request by magik6k**
Fixes #16

* `getProjectAction` isn't called in pipeline projects, making `project` variable null (this caused #16)
*  ProjectActions need to implement SimpleBuildStep.LastBuildAction and we need to add them to run in perform to let Jenkins know about them
   * See https://github.com/jenkinsci/gatling-plugin/blob/master/src/main/java/io/gatling/jenkins/GatlingBuildAction.java#L31-L40 for better explanation
   * Without this the icon wouldn't show up and you couldn't view the results.

### CODE REVIEW

File: src/main/java/org/jenkinsci/plugins/benchmark/core/BenchmarkPublisher.java [hunk 1]
```diff
@@ -234,7 +222,7 @@ public void perform(@Nonnull Run<?, ?> run, @Nonnull FilePath filePath, @Nonnull
         }
         if (failed) {
             taskListener.getLogger().println(Messages.BenchmarkPublisher_CollectionSuccessButValidationFailure());
-            run.setResult(Result.FAILURE);
+            run.setResult(Result.UNSTABLE);
```
Comment (magik6k) [inline src/main/java/org/jenkinsci/plugins/benchmark/core/BenchmarkPublisher.java]: Note this change. This is somewhat subjective, if you want I can remove and/or split this change into separate commit/PR.

With this the plugin behaves more like other testing plugins, giving the build a yellow icon when the check failed.

**Comment by magik6k** [comment]
(I did manually test these changes on both pipeline and freestyle projects and it seems to work fine)

File: src/main/java/org/jenkinsci/plugins/benchmark/core/BenchmarkPublisher.java (hunk 1 above)
Comment (damercie) [reply src/main/java/org/jenkinsci/plugins/benchmark/core/BenchmarkPublisher.java]: Saw that change, no issue with it. My only concern is the adding of actions inside the perform sections.

Comment (damercie) [reply src/main/java/org/jenkinsci/plugins/benchmark/core/BenchmarkPublisher.java]: Going ahead with the merge.

**Comment by damercie** [comment]
@magik6k  I ran my own tests. Looks good. Thank you for the fix.

**Comment by damercie** [comment]
@magik6k Pushed the new version (v1.0.6) to Jenkins artifactory, should appear soon inside Jenkins Plugin manager as an update.
